---
- name: Configurar UFW en los nodos del clúster
  hosts: all
  become: true
  tasks:
    - name: Permitir conexiones SSH antes de habilitar el firewall
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Permitir tráfico HTTP para Nginx
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Habilitar UFW y establecer políticas por defecto
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming
