---
- name: Actualizar todos los servidores
  hosts: servidores
  become: yes
  tasks:
    - name: Esperar a que el gestor de paquetes se libere y actualizar caché
      apt:
        update_cache: yes
        upgrade: safe
      register: apt_result
      until: apt_result is success
      retries: 5
      delay: 10
