---
- name: Gestionar usuarios y accesos en los servidores
  hosts: servidores
  become: true
  tasks:
    - name: Crear un usuario operador estándar
      ansible.builtin.user:
        name: devops
        comment: "Usuario Operador DevOps"
        shell: /bin/bash
        create_home: true
        state: present

    - name: Permitir que el usuario devops ejecute sudo sin contraseña
      ansible.builtin.copy:
        dest: /etc/sudoers.d/devops
        content: "devops ALL=(ALL) NOPASSWD: ALL"
        mode: "0440"
