---
- name: Asegurar que el grupo de administración exista
  ansible.builtin.group:
    name: "{{ admin_group }}"
    state: present

- name: Crear usuario administrador estándar
  ansible.builtin.user:
    name: "{{ admin_user }}"
    group: "{{ admin_group }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Configurar permisos de Sudoers sin contraseña para el usuario administrador
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ admin_user }}"
    content: "{{ admin_user }} ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'
    validate: 'visudo -cf %s'
