---
all:
  hosts:
    node01:
      ansible_host: 172.30.2.2
    node02:
      ansible_host: 172.30.2.3
    node03:
      ansible_host: 172.30.2.4
    node04:
      ansible_host: 172.30.2.5
    node05:
      ansible_host: 172.30.2.6
  children:
    servidores:
      hosts:
        node01:
        node02:
        node03:
        node04:
        node05:
